import { ITypography, Typography } from "../Typography";
import { IColors, DARK_COLORS, LIGHT_COLORS } from "../Colors";
import {
  IDividers,
  IDividersColors,
  IBorders,
  IShadows,
  IBlur,
  DIVIDERS_COLOR_DARK,
  DIVIDERS_COLOR_LIGHT,
  DIVIDERS_DARK,
  DIVIDERS_LIGHT,
  BORDERS_DARK,
  BORDERS_LIGHT,
  SHADOWS_DARK,
  SHADOWS_LIGHT,
  BLUR
} from "../effects";
import { IShape, Shape } from "../Shape";
import { IZIndex, ZINDEX } from "../ZIndex";

export type TThemeColors = IColors & {
  backgroundPrimaryMain: string;
  backgroundSecondaryGreen: string;
  backgroundSecondaryPurple: string;
  backgroundSecondaryYellow: string;
  backgroundSecondaryBlue: string;
  backgroundSecondaryAmber: string;
  backgroundSecondaryRed: string;
  backgroundSecondaryCyan: string;
  backgroundSecondaryTeal: string;
  backgroundSecondaryOrange: string;
  backgroundSecondaryNeutral: string;
  backgroundTetriary0: string;
  backgroundTetriary1: string;
  componentPrimaryGreenDefault: string;
  componentPrimaryGreenHover: string;
  componentPrimaryGreenPressed: string;
  componentPrimaryPurpleDefault: string;
  componentPrimaryPurpleHover: string;
  componentPrimaryPurplePressed: string;
  componentPrimaryNeutralDefault: string;
  componentPrimaryNeutralHover: string;
  componentPrimaryNeutralPressed: string;
  componentPrimaryYellowDefault: string;
  componentPrimaryYellowHover: string;
  componentPrimaryYellowPressed: string;
  componentPrimaryBlueDefault: string;
  componentPrimaryBlueHover: string;
  componentPrimaryBluePressed: string;
  componentPrimaryAmberDefault: string;
  componentPrimaryAmberHover: string;
  componentPrimaryAmberPressed: string;
  componentPrimaryRedDefault: string;
  componentPrimaryRedHover: string;
  componentPrimaryRedPressed: string;
  componentPrimaryCyanDefault: string;
  componentPrimaryCyanHover: string;
  componentPrimaryCyanPressed: string;
  componentPrimaryTealDefault: string;
  componentPrimaryTealHover: string;
  componentPrimaryTealPressed: string;
  componentPrimaryOrangeDefault: string;
  componentPrimaryOrangeHover: string;
  componentPrimaryOrangePressed: string;
  componentSecondaryGreenDefault: string;
  componentSecondaryGreenHover: string;
  componentSecondaryGreenPressed: string;
  componentSecondaryPurpleDefault: string;
  componentSecondaryPurpleHover: string;
  componentSecondaryPurplePressed: string;
  componentSecondaryNeutralDefault: string;
  componentSecondaryNeutralHover: string;
  componentSecondaryNeutralPressed: string;
  componentSecondaryYellowDefault: string;
  componentSecondaryYellowHover: string;
  componentSecondaryYellowPressed: string;
  componentSecondaryBlueDefault: string;
  componentSecondaryBlueHover: string;
  componentSecondaryBluePressed: string;
  componentSecondaryAmberDefault: string;
  componentSecondaryAmberHover: string;
  componentSecondaryAmberPressed: string;
  componentSecondaryRedDefault: string;
  componentSecondaryRedHover: string;
  componentSecondaryRedPressed: string;
  componentSecondaryCyanDefault: string;
  componentSecondaryCyanHover: string;
  componentSecondaryCyanPressed: string;
  componentSecondaryTealDefault: string;
  componentSecondaryTealHover: string;
  componentSecondaryTealPressed: string;
  componentSecondaryOrangeDefault: string;
  componentSecondaryOrangeHover: string;
  componentSecondaryOrangePressed: string;
  componentTooltipBackground: string;
  componentTooltipHelpTextColor: string;
  componentTooltipTextColor: string;
  textBasicDefault: string;
  textBasicDisabled: string;
  textBasicExtra: string;
  textBasicHover: string;
  textBasicPressed: string;
  textColoredGreen: string;
  textColoredPurple: string;
  textColoredYellow: string;
  textColoredBlue: string;
  textColoredAmber: string;
  textColoredRed: string;
  textColoredCyan: string;
  textColoredTeal: string;
  textColoredOrange: string;
};

const colorsLight: TThemeColors = {
  ...LIGHT_COLORS,
  backgroundPrimaryMain: LIGHT_COLORS.neutral0,
  backgroundSecondaryNeutral: LIGHT_COLORS.neutral1,
  backgroundSecondaryBlue: LIGHT_COLORS.blue7,
  backgroundSecondaryTeal: LIGHT_COLORS.teal7,
  backgroundSecondaryRed: LIGHT_COLORS.red7,
  backgroundSecondaryAmber: LIGHT_COLORS.amber7,
  backgroundSecondaryYellow: LIGHT_COLORS.yellow7,
  backgroundSecondaryGreen: LIGHT_COLORS.green7,
  backgroundSecondaryCyan: LIGHT_COLORS.cyan7,
  backgroundSecondaryPurple: LIGHT_COLORS.purple7,
  backgroundSecondaryOrange: LIGHT_COLORS.orange7,
  backgroundTetriary0: LIGHT_COLORS.neutral0,
  backgroundTetriary1: LIGHT_COLORS.neutral1,
  textBasicDefault: LIGHT_COLORS.neutral10,
  textBasicHover: LIGHT_COLORS.neutral8,
  textBasicPressed: LIGHT_COLORS.neutral12,
  textBasicDisabled: LIGHT_COLORS.neutral5,
  textBasicExtra: LIGHT_COLORS.neutral0,
  textColoredBlue: LIGHT_COLORS.blue9,
  textColoredTeal: LIGHT_COLORS.teal9,
  textColoredRed: LIGHT_COLORS.red9,
  textColoredAmber: LIGHT_COLORS.amber9,
  textColoredYellow: LIGHT_COLORS.yellow9,
  textColoredGreen: LIGHT_COLORS.green9,
  textColoredCyan: LIGHT_COLORS.cyan9,
  textColoredPurple: LIGHT_COLORS.purple9,
  textColoredOrange: LIGHT_COLORS.orange9,
  componentPrimaryBlueDefault: LIGHT_COLORS.blue1,
  componentPrimaryBlueHover: LIGHT_COLORS.blue8,
  componentPrimaryBluePressed: LIGHT_COLORS.blue9,
  componentPrimaryTealDefault: LIGHT_COLORS.teal1,
  componentPrimaryTealHover: LIGHT_COLORS.teal8,
  componentPrimaryTealPressed: LIGHT_COLORS.teal9,
  componentPrimaryRedDefault: LIGHT_COLORS.red1,
  componentPrimaryRedHover: LIGHT_COLORS.red8,
  componentPrimaryRedPressed: LIGHT_COLORS.red9,
  componentPrimaryAmberDefault: LIGHT_COLORS.amber1,
  componentPrimaryAmberHover: LIGHT_COLORS.amber8,
  componentPrimaryAmberPressed: LIGHT_COLORS.amber9,
  componentPrimaryYellowDefault: LIGHT_COLORS.yellow1,
  componentPrimaryYellowHover: LIGHT_COLORS.yellow8,
  componentPrimaryYellowPressed: LIGHT_COLORS.yellow9,
  componentPrimaryGreenDefault: LIGHT_COLORS.green1,
  componentPrimaryGreenHover: LIGHT_COLORS.green8,
  componentPrimaryGreenPressed: LIGHT_COLORS.green9,
  componentPrimaryCyanDefault: LIGHT_COLORS.cyan1,
  componentPrimaryCyanHover: LIGHT_COLORS.cyan8,
  componentPrimaryCyanPressed: LIGHT_COLORS.cyan9,
  componentPrimaryPurpleDefault: LIGHT_COLORS.purple1,
  componentPrimaryPurpleHover: LIGHT_COLORS.purple8,
  componentPrimaryPurplePressed: LIGHT_COLORS.purple9,
  componentPrimaryOrangeDefault: LIGHT_COLORS.orange1,
  componentPrimaryOrangeHover: LIGHT_COLORS.orange8,
  componentPrimaryOrangePressed: LIGHT_COLORS.orange9,
  componentPrimaryNeutralDefault: LIGHT_COLORS.neutral4,
  componentPrimaryNeutralHover: LIGHT_COLORS.neutral6,
  componentPrimaryNeutralPressed: LIGHT_COLORS.neutral5,
  componentSecondaryBlueDefault: LIGHT_COLORS.blue6,
  componentSecondaryBlueHover: LIGHT_COLORS.blue5,
  componentSecondaryBluePressed: LIGHT_COLORS.blue4,
  componentSecondaryTealDefault: LIGHT_COLORS.teal6,
  componentSecondaryTealHover: LIGHT_COLORS.teal5,
  componentSecondaryTealPressed: LIGHT_COLORS.teal4,
  componentSecondaryRedDefault: LIGHT_COLORS.red6,
  componentSecondaryRedHover: LIGHT_COLORS.red5,
  componentSecondaryRedPressed: LIGHT_COLORS.red4,
  componentSecondaryAmberDefault: LIGHT_COLORS.amber6,
  componentSecondaryAmberHover: LIGHT_COLORS.amber5,
  componentSecondaryAmberPressed: LIGHT_COLORS.amber4,
  componentSecondaryYellowDefault: LIGHT_COLORS.yellow6,
  componentSecondaryYellowHover: LIGHT_COLORS.yellow5,
  componentSecondaryYellowPressed: LIGHT_COLORS.yellow4,
  componentSecondaryGreenDefault: LIGHT_COLORS.green6,
  componentSecondaryGreenHover: LIGHT_COLORS.green5,
  componentSecondaryGreenPressed: LIGHT_COLORS.green4,
  componentSecondaryCyanDefault: LIGHT_COLORS.cyan6,
  componentSecondaryCyanHover: LIGHT_COLORS.cyan5,
  componentSecondaryCyanPressed: LIGHT_COLORS.cyan4,
  componentSecondaryPurpleDefault: LIGHT_COLORS.purple6,
  componentSecondaryPurpleHover: LIGHT_COLORS.purple5,
  componentSecondaryPurplePressed: LIGHT_COLORS.purple4,
  componentSecondaryOrangeDefault: LIGHT_COLORS.orange6,
  componentSecondaryOrangeHover: LIGHT_COLORS.orange5,
  componentSecondaryOrangePressed: LIGHT_COLORS.orange4,
  componentSecondaryNeutralDefault: LIGHT_COLORS.neutral2,
  componentSecondaryNeutralHover: LIGHT_COLORS.neutral4,
  componentSecondaryNeutralPressed: LIGHT_COLORS.neutral6,
  componentTooltipBackground: LIGHT_COLORS.neutral10,
  componentTooltipTextColor: LIGHT_COLORS.neutral1,
  componentTooltipHelpTextColor: LIGHT_COLORS.neutral2,
  blue1: LIGHT_COLORS.blue7,
  blue2: LIGHT_COLORS.blue6,
  blue3: LIGHT_COLORS.blue5,
  blue4: LIGHT_COLORS.blue4,
  blue5: LIGHT_COLORS.blue3,
  blue6: LIGHT_COLORS.blue2,
  blue7: LIGHT_COLORS.blue1,
  blue8: LIGHT_COLORS.blue8,
  blue9: LIGHT_COLORS.blue9,
  blue10: LIGHT_COLORS.blue10,
  blue11: LIGHT_COLORS.blue11,
  blue12: LIGHT_COLORS.blue12,
  blue13: LIGHT_COLORS.blue13,
  blue14: LIGHT_COLORS.blue14,
  teal1: LIGHT_COLORS.teal7,
  teal2: LIGHT_COLORS.teal6,
  teal3: LIGHT_COLORS.teal5,
  teal4: LIGHT_COLORS.teal4,
  teal5: LIGHT_COLORS.teal3,
  teal6: LIGHT_COLORS.teal2,
  teal7: LIGHT_COLORS.teal1,
  teal8: LIGHT_COLORS.teal8,
  teal9: LIGHT_COLORS.teal9,
  teal10: LIGHT_COLORS.teal10,
  teal11: LIGHT_COLORS.teal11,
  teal12: LIGHT_COLORS.teal12,
  teal13: LIGHT_COLORS.teal13,
  teal14: LIGHT_COLORS.teal14,
  red1: LIGHT_COLORS.red7,
  red2: LIGHT_COLORS.red6,
  red3: LIGHT_COLORS.red5,
  red4: LIGHT_COLORS.red4,
  red5: LIGHT_COLORS.red3,
  red6: LIGHT_COLORS.red2,
  red7: LIGHT_COLORS.red1,
  red8: LIGHT_COLORS.red8,
  red9: LIGHT_COLORS.red9,
  red10: LIGHT_COLORS.red10,
  red11: LIGHT_COLORS.red11,
  red12: LIGHT_COLORS.red12,
  red13: LIGHT_COLORS.red13,
  red14: LIGHT_COLORS.red14,
  amber1: LIGHT_COLORS.amber7,
  amber2: LIGHT_COLORS.amber6,
  amber3: LIGHT_COLORS.amber5,
  amber4: LIGHT_COLORS.amber4,
  amber5: LIGHT_COLORS.amber3,
  amber6: LIGHT_COLORS.amber2,
  amber7: LIGHT_COLORS.amber1,
  amber8: LIGHT_COLORS.amber8,
  amber9: LIGHT_COLORS.amber9,
  amber10: LIGHT_COLORS.amber10,
  amber11: LIGHT_COLORS.amber11,
  amber12: LIGHT_COLORS.amber12,
  amber13: LIGHT_COLORS.amber13,
  amber14: LIGHT_COLORS.amber14,
  yellow1: LIGHT_COLORS.yellow7,
  yellow2: LIGHT_COLORS.yellow6,
  yellow3: LIGHT_COLORS.yellow5,
  yellow4: LIGHT_COLORS.yellow4,
  yellow5: LIGHT_COLORS.yellow3,
  yellow6: LIGHT_COLORS.yellow2,
  yellow7: LIGHT_COLORS.yellow1,
  yellow8: LIGHT_COLORS.yellow8,
  yellow9: LIGHT_COLORS.yellow9,
  yellow10: LIGHT_COLORS.yellow10,
  yellow11: LIGHT_COLORS.yellow11,
  yellow12: LIGHT_COLORS.yellow12,
  yellow13: LIGHT_COLORS.yellow13,
  yellow14: LIGHT_COLORS.yellow14,
  green1: LIGHT_COLORS.green7,
  green2: LIGHT_COLORS.green6,
  green3: LIGHT_COLORS.green5,
  green4: LIGHT_COLORS.green4,
  green5: LIGHT_COLORS.green3,
  green6: LIGHT_COLORS.green2,
  green7: LIGHT_COLORS.green1,
  green8: LIGHT_COLORS.green8,
  green9: LIGHT_COLORS.green9,
  green10: LIGHT_COLORS.green10,
  green11: LIGHT_COLORS.green11,
  green12: LIGHT_COLORS.green12,
  green13: LIGHT_COLORS.green13,
  green14: LIGHT_COLORS.green14,
  cyan1: LIGHT_COLORS.cyan7,
  cyan2: LIGHT_COLORS.cyan6,
  cyan3: LIGHT_COLORS.cyan5,
  cyan4: LIGHT_COLORS.cyan4,
  cyan5: LIGHT_COLORS.cyan3,
  cyan6: LIGHT_COLORS.cyan2,
  cyan7: LIGHT_COLORS.cyan1,
  cyan8: LIGHT_COLORS.cyan8,
  cyan9: LIGHT_COLORS.cyan9,
  cyan10: LIGHT_COLORS.cyan10,
  cyan11: LIGHT_COLORS.cyan11,
  cyan12: LIGHT_COLORS.cyan12,
  cyan13: LIGHT_COLORS.cyan13,
  cyan14: LIGHT_COLORS.cyan14,
  purple1: LIGHT_COLORS.purple7,
  purple2: LIGHT_COLORS.purple6,
  purple3: LIGHT_COLORS.purple5,
  purple4: LIGHT_COLORS.purple4,
  purple5: LIGHT_COLORS.purple3,
  purple6: LIGHT_COLORS.purple2,
  purple7: LIGHT_COLORS.purple1,
  purple8: LIGHT_COLORS.purple8,
  purple9: LIGHT_COLORS.purple9,
  purple10: LIGHT_COLORS.purple10,
  purple11: LIGHT_COLORS.purple11,
  purple12: LIGHT_COLORS.purple12,
  purple13: LIGHT_COLORS.purple13,
  purple14: LIGHT_COLORS.purple14,
  orange1: LIGHT_COLORS.orange7,
  orange2: LIGHT_COLORS.orange6,
  orange3: LIGHT_COLORS.orange5,
  orange4: LIGHT_COLORS.orange4,
  orange5: LIGHT_COLORS.orange3,
  orange6: LIGHT_COLORS.orange2,
  orange7: LIGHT_COLORS.orange1,
  orange8: LIGHT_COLORS.orange8,
  orange9: LIGHT_COLORS.orange9,
  orange10: LIGHT_COLORS.orange10,
  orange11: LIGHT_COLORS.orange11,
  orange12: LIGHT_COLORS.orange12,
  orange13: LIGHT_COLORS.orange13,
  orange14: LIGHT_COLORS.orange14
};

const colorsDark: TThemeColors = {
  ...DARK_COLORS,
  backgroundPrimaryMain: DARK_COLORS.neutral0,
  backgroundSecondaryNeutral: DARK_COLORS.neutral1,
  backgroundSecondaryBlue: DARK_COLORS.blue6,
  backgroundSecondaryTeal: DARK_COLORS.teal6,
  backgroundSecondaryRed: DARK_COLORS.red6,
  backgroundSecondaryAmber: DARK_COLORS.amber6,
  backgroundSecondaryYellow: DARK_COLORS.yellow6,
  backgroundSecondaryGreen: DARK_COLORS.green6,
  backgroundSecondaryCyan: DARK_COLORS.cyan6,
  backgroundSecondaryPurple: DARK_COLORS.purple6,
  backgroundSecondaryOrange: DARK_COLORS.orange6,
  backgroundTetriary0: DARK_COLORS.neutral3,
  backgroundTetriary1: DARK_COLORS.neutral3,
  textBasicDefault: DARK_COLORS.neutral10,
  textBasicHover: DARK_COLORS.neutral8,
  textBasicPressed: DARK_COLORS.neutral12,
  textBasicDisabled: DARK_COLORS.neutral5,
  textBasicExtra: DARK_COLORS.neutral0,
  textColoredBlue: DARK_COLORS.blue9,
  textColoredTeal: DARK_COLORS.teal9,
  textColoredRed: DARK_COLORS.red9,
  textColoredAmber: DARK_COLORS.amber9,
  textColoredYellow: DARK_COLORS.yellow9,
  textColoredGreen: DARK_COLORS.green9,
  textColoredCyan: DARK_COLORS.cyan9,
  textColoredPurple: DARK_COLORS.purple9,
  textColoredOrange: DARK_COLORS.orange9,
  componentPrimaryBlueDefault: DARK_COLORS.blue10,
  componentPrimaryBlueHover: DARK_COLORS.blue9,
  componentPrimaryBluePressed: DARK_COLORS.blue8,
  componentPrimaryTealDefault: DARK_COLORS.teal10,
  componentPrimaryTealHover: DARK_COLORS.teal9,
  componentPrimaryTealPressed: DARK_COLORS.teal8,
  componentPrimaryRedDefault: DARK_COLORS.red10,
  componentPrimaryRedHover: DARK_COLORS.red9,
  componentPrimaryRedPressed: DARK_COLORS.red8,
  componentPrimaryAmberDefault: DARK_COLORS.amber10,
  componentPrimaryAmberHover: DARK_COLORS.amber9,
  componentPrimaryAmberPressed: DARK_COLORS.amber8,
  componentPrimaryYellowDefault: DARK_COLORS.yellow10,
  componentPrimaryYellowHover: DARK_COLORS.yellow9,
  componentPrimaryYellowPressed: DARK_COLORS.yellow8,
  componentPrimaryGreenDefault: DARK_COLORS.green10,
  componentPrimaryGreenHover: DARK_COLORS.green9,
  componentPrimaryGreenPressed: DARK_COLORS.green8,
  componentPrimaryCyanDefault: DARK_COLORS.cyan10,
  componentPrimaryCyanHover: DARK_COLORS.cyan9,
  componentPrimaryCyanPressed: DARK_COLORS.cyan8,
  componentPrimaryPurpleDefault: DARK_COLORS.purple10,
  componentPrimaryPurpleHover: DARK_COLORS.purple9,
  componentPrimaryPurplePressed: DARK_COLORS.purple8,
  componentPrimaryOrangeDefault: DARK_COLORS.orange10,
  componentPrimaryOrangeHover: DARK_COLORS.orange9,
  componentPrimaryOrangePressed: DARK_COLORS.orange8,
  componentPrimaryNeutralDefault: DARK_COLORS.neutral5,
  componentPrimaryNeutralHover: DARK_COLORS.neutral6,
  componentPrimaryNeutralPressed: DARK_COLORS.neutral4,
  componentSecondaryBlueDefault: DARK_COLORS.blue3,
  componentSecondaryBlueHover: DARK_COLORS.blue4,
  componentSecondaryBluePressed: DARK_COLORS.blue5,
  componentSecondaryTealDefault: DARK_COLORS.teal3,
  componentSecondaryTealHover: DARK_COLORS.teal4,
  componentSecondaryTealPressed: DARK_COLORS.teal5,
  componentSecondaryRedDefault: DARK_COLORS.red3,
  componentSecondaryRedHover: DARK_COLORS.red4,
  componentSecondaryRedPressed: DARK_COLORS.red5,
  componentSecondaryAmberDefault: DARK_COLORS.amber3,
  componentSecondaryAmberHover: DARK_COLORS.amber4,
  componentSecondaryAmberPressed: DARK_COLORS.amber5,
  componentSecondaryYellowDefault: DARK_COLORS.yellow3,
  componentSecondaryYellowHover: DARK_COLORS.yellow4,
  componentSecondaryYellowPressed: DARK_COLORS.yellow5,
  componentSecondaryGreenDefault: DARK_COLORS.green3,
  componentSecondaryGreenHover: DARK_COLORS.green4,
  componentSecondaryGreenPressed: DARK_COLORS.green5,
  componentSecondaryCyanDefault: DARK_COLORS.cyan3,
  componentSecondaryCyanHover: DARK_COLORS.cyan4,
  componentSecondaryCyanPressed: DARK_COLORS.cyan5,
  componentSecondaryPurpleDefault: DARK_COLORS.purple3,
  componentSecondaryPurpleHover: DARK_COLORS.purple4,
  componentSecondaryPurplePressed: DARK_COLORS.purple5,
  componentSecondaryOrangeDefault: DARK_COLORS.orange3,
  componentSecondaryOrangeHover: DARK_COLORS.orange4,
  componentSecondaryOrangePressed: DARK_COLORS.orange5,
  componentSecondaryNeutralDefault: DARK_COLORS.neutral6,
  componentSecondaryNeutralHover: DARK_COLORS.neutral4,
  componentSecondaryNeutralPressed: DARK_COLORS.neutral2,
  componentTooltipBackground: DARK_COLORS.neutral4,
  componentTooltipTextColor: DARK_COLORS.neutral12,
  componentTooltipHelpTextColor: DARK_COLORS.neutral10,
  blue1: DARK_COLORS.blue6,
  blue2: DARK_COLORS.blue5,
  blue3: DARK_COLORS.blue4,
  blue4: DARK_COLORS.blue3,
  blue5: DARK_COLORS.blue2,
  blue6: DARK_COLORS.blue1,
  blue7: DARK_COLORS.blue8,
  blue8: DARK_COLORS.blue9,
  blue9: DARK_COLORS.blue10,
  blue10: DARK_COLORS.blue11,
  blue11: DARK_COLORS.blue12,
  blue12: DARK_COLORS.blue13,
  blue13: DARK_COLORS.blue13,
  blue14: DARK_COLORS.blue14,
  teal1: DARK_COLORS.teal6,
  teal2: DARK_COLORS.teal5,
  teal3: DARK_COLORS.teal4,
  teal4: DARK_COLORS.teal3,
  teal5: DARK_COLORS.teal2,
  teal6: DARK_COLORS.teal1,
  teal7: DARK_COLORS.teal8,
  teal8: DARK_COLORS.teal9,
  teal9: DARK_COLORS.teal10,
  teal10: DARK_COLORS.teal11,
  teal11: DARK_COLORS.teal12,
  teal12: DARK_COLORS.teal13,
  teal13: DARK_COLORS.teal13,
  teal14: DARK_COLORS.teal14,
  red1: DARK_COLORS.red6,
  red2: DARK_COLORS.red5,
  red3: DARK_COLORS.red4,
  red4: DARK_COLORS.red3,
  red5: DARK_COLORS.red2,
  red6: DARK_COLORS.red1,
  red7: DARK_COLORS.red8,
  red8: DARK_COLORS.red9,
  red9: DARK_COLORS.red10,
  red10: DARK_COLORS.red11,
  red11: DARK_COLORS.red12,
  red12: DARK_COLORS.red13,
  red13: DARK_COLORS.red13,
  red14: DARK_COLORS.red14,
  amber1: DARK_COLORS.amber6,
  amber2: DARK_COLORS.amber5,
  amber3: DARK_COLORS.amber4,
  amber4: DARK_COLORS.amber3,
  amber5: DARK_COLORS.amber2,
  amber6: DARK_COLORS.amber1,
  amber7: DARK_COLORS.amber8,
  amber8: DARK_COLORS.amber9,
  amber9: DARK_COLORS.amber10,
  amber10: DARK_COLORS.amber11,
  amber11: DARK_COLORS.amber12,
  amber12: DARK_COLORS.amber13,
  amber13: DARK_COLORS.amber13,
  amber14: DARK_COLORS.amber14,
  yellow1: DARK_COLORS.yellow6,
  yellow2: DARK_COLORS.yellow5,
  yellow3: DARK_COLORS.yellow4,
  yellow4: DARK_COLORS.yellow3,
  yellow5: DARK_COLORS.yellow2,
  yellow6: DARK_COLORS.yellow1,
  yellow7: DARK_COLORS.yellow8,
  yellow8: DARK_COLORS.yellow9,
  yellow9: DARK_COLORS.yellow10,
  yellow10: DARK_COLORS.yellow11,
  yellow11: DARK_COLORS.yellow12,
  yellow12: DARK_COLORS.yellow13,
  yellow13: DARK_COLORS.yellow13,
  yellow14: DARK_COLORS.yellow14,
  green1: DARK_COLORS.green6,
  green2: DARK_COLORS.green5,
  green3: DARK_COLORS.green4,
  green4: DARK_COLORS.green3,
  green5: DARK_COLORS.green2,
  green6: DARK_COLORS.green1,
  green7: DARK_COLORS.green8,
  green8: DARK_COLORS.green9,
  green9: DARK_COLORS.green10,
  green10: DARK_COLORS.green11,
  green11: DARK_COLORS.green12,
  green12: DARK_COLORS.green13,
  green13: DARK_COLORS.green13,
  green14: DARK_COLORS.green14,
  cyan1: DARK_COLORS.cyan6,
  cyan2: DARK_COLORS.cyan5,
  cyan3: DARK_COLORS.cyan4,
  cyan4: DARK_COLORS.cyan3,
  cyan5: DARK_COLORS.cyan2,
  cyan6: DARK_COLORS.cyan1,
  cyan7: DARK_COLORS.cyan8,
  cyan8: DARK_COLORS.cyan9,
  cyan9: DARK_COLORS.cyan10,
  cyan10: DARK_COLORS.cyan11,
  cyan11: DARK_COLORS.cyan12,
  cyan12: DARK_COLORS.cyan13,
  cyan13: DARK_COLORS.cyan13,
  cyan14: DARK_COLORS.cyan14,
  purple1: DARK_COLORS.purple6,
  purple2: DARK_COLORS.purple5,
  purple3: DARK_COLORS.purple4,
  purple4: DARK_COLORS.purple3,
  purple5: DARK_COLORS.purple2,
  purple6: DARK_COLORS.purple1,
  purple7: DARK_COLORS.purple8,
  purple8: DARK_COLORS.purple9,
  purple9: DARK_COLORS.purple10,
  purple10: DARK_COLORS.purple11,
  purple11: DARK_COLORS.purple12,
  purple12: DARK_COLORS.purple13,
  purple13: DARK_COLORS.purple13,
  purple14: DARK_COLORS.purple14,
  orange1: DARK_COLORS.orange6,
  orange2: DARK_COLORS.orange5,
  orange3: DARK_COLORS.orange4,
  orange4: DARK_COLORS.orange3,
  orange5: DARK_COLORS.orange2,
  orange6: DARK_COLORS.orange1,
  orange7: DARK_COLORS.orange8,
  orange8: DARK_COLORS.orange9,
  orange9: DARK_COLORS.orange10,
  orange10: DARK_COLORS.orange11,
  orange11: DARK_COLORS.orange12,
  orange12: DARK_COLORS.orange13,
  orange13: DARK_COLORS.orange13,
  orange14: DARK_COLORS.orange14
};

export interface ITheme {
  colors: TThemeColors;
  dividers: IDividers;
  dividersColors: IDividersColors;
  name: string;
  borders: IBorders;
  shadows: IShadows;
  blur: IBlur;
  shape: IShape;
  typography: ITypography;
  colorIcon: string;
  zindex: IZIndex;
}

export const LIGHT_THEME: ITheme = {
  colors: colorsLight,
  dividers: DIVIDERS_LIGHT,
  dividersColors: DIVIDERS_COLOR_LIGHT,
  name: "light",
  borders: BORDERS_LIGHT,
  shadows: SHADOWS_LIGHT,
  blur: BLUR,
  shape: Shape,
  typography: Typography,
  colorIcon: LIGHT_COLORS.neutral12,
  zindex: ZINDEX
};

export const DARK_THEME: ITheme = {
  colors: colorsDark,
  dividers: DIVIDERS_DARK,
  dividersColors: DIVIDERS_COLOR_DARK,
  name: "dark",
  borders: BORDERS_DARK,
  shadows: SHADOWS_DARK,
  blur: BLUR,
  shape: Shape,
  typography: Typography,
  colorIcon: DARK_COLORS.neutral12,
  zindex: ZINDEX
};

export const DEFAULT_THEME: ITheme = {
  colors: colorsLight,
  dividers: DIVIDERS_LIGHT,
  dividersColors: DIVIDERS_COLOR_LIGHT,
  name: "light",
  borders: BORDERS_LIGHT,
  shadows: SHADOWS_LIGHT,
  blur: BLUR,
  shape: Shape,
  typography: Typography,
  colorIcon: LIGHT_COLORS.neutral12,
  zindex: ZINDEX
};
