import React from "react";
import {
  IconDoc,
  IconDocx,
  IconXls,
  IconXlsx,
  IconPpt,
  IconPptx,
  IconZip,
  IconRar,
  IconTxt,
  IconPdf,
  IconWebp,
  IconBmp,
  IconGif,
  IconJpg,
  IconJpeg,
  IconPng,
  IconTiff,
  Icon3Gp,
  IconAvi,
  IconMov,
  IconMp4,
  IconM4V,
  IconM4A,
  IconMp3,
  IconMkv,
  IconOgm,
  IconOgv,
  IconOgg,
  IconOga,
  IconWebm,
  IconWav
} from "@dmitrygrigorov/icons";

export const mapExtensionToIcon: {
  [value: string]: React.FC<React.SVGProps<SVGSVGElement>>;
} = {
  doc: IconDoc,
  docx: IconDocx,
  xls: IconXls,
  xlsx: IconXlsx,
  ppt: IconPpt,
  pptx: IconPptx,
  zip: IconZip,
  rar: IconRar,
  txt: IconTxt,
  pdf: IconPdf,
  webp: IconWebp,
  bmp: IconBmp,
  gif: IconGif,
  jpg: IconJpg,
  jpeg: IconJpeg,
  png: IconPng,
  tiff: IconTiff,
  "3gp": Icon3Gp,
  avi: IconAvi,
  mov: IconMov,
  mp4: IconMp4,
  m4v: IconM4V,
  m4a: IconM4A,
  mp3: IconMp3,
  mkv: IconMkv,
  ogm: IconOgm,
  ogv: IconOgv,
  ogg: IconOgg,
  oga: IconOga,
  wav: IconWav,
  webm: IconWebm
};
