export interface ITypography {
  fontFamily?: string;
  fontSize2xs: string;
  fontSizeXs: string;
  fontSizeS: string;
  fontSizeM: string;
  fontSizeL: string;
  fontSizeXl: string;
  fontSize2xl: string;
  fontSize3xl: string;
  fontSize4xl: string;
  fontSize5xl: string;
  fontSize6xl: string;
  lineHeight3xs: string;
  lineHeight2xs: string;
  lineHeightXs: string;
  lineHeightS: string;
  lineHeightM: string;
  lineHeightL: string;
  lineHeightXl: string;
  lineHeight2xl: string;
  lineHeight3xl: string;
  lineHeight4xl: string;
  lineHeight5xl: string;
  lineHeight6xl: string;
  fontWeightThin: number;
  fontWeightExtraLight: number;
  fontWeightLight: number;
  fontWeightRegular: number;
  fontWeightMedium: number;
  fontWeightSemibold: number;
  fontWeightBold: number;
  fontWeightExtraBold: number;
  fontWeightBlack: number;
}

export const Typography: ITypography = {
  fontFamily: "Onest",
  fontSize2xs: "10px",
  fontSizeXs: "12px",
  fontSizeS: "14px",
  fontSizeM: "16px",
  fontSizeL: "20px",
  fontSizeXl: "24px",
  fontSize2xl: "28px",
  fontSize3xl: "32px",
  fontSize4xl: "40px",
  fontSize5xl: "56px",
  fontSize6xl: "64px",
  lineHeight3xs: "14px",
  lineHeight2xs: "16px",
  lineHeightXs: "20px",
  lineHeightS: "22px",
  lineHeightM: "24px",
  lineHeightL: "28px",
  lineHeightXl: "32px",
  lineHeight2xl: "36px",
  lineHeight3xl: "40px",
  lineHeight4xl: "48px",
  lineHeight5xl: "56px",
  lineHeight6xl: "64px",
  fontWeightThin: 100,
  fontWeightExtraLight: 200,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightSemibold: 600,
  fontWeightBold: 700,
  fontWeightExtraBold: 800,
  fontWeightBlack: 900
};
