import React, { useMemo, useState } from "react";
import { IComponentStand } from "../../types";
// This module is generated by src/site/build/script.js before the site starts.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

import * as componentsPages from "../../build/components";
import {
  CatalogCard,
  CatalogCardDescription,
  CatalogCardFooter,
  CatalogCardHeader,
  CatalogCardLabel,
  CatalogCardName,
  CatalogControls,
  CatalogEyebrow,
  CatalogHero,
  CatalogHeroCopy,
  CatalogIntro,
  CatalogPage,
  CatalogResponsiveStyles,
  CatalogTitle,
  CategoryButton,
  CategoryCount,
  CategoryFilters,
  ClearSearchButton,
  EmptyState,
  EmptyStateButton,
  EmptyStateMark,
  ReleaseBadge,
  ResultsGrid,
  ResultsHeader,
  ResultsItem,
  ResultsSummary,
  SearchField,
  SearchIcon,
  SearchInput,
  SearchLabel,
  Stat,
  StatLabel,
  StatValue,
  Stats,
  ViewLabel
} from "./styles";

type TCategoryId =
  | "forms"
  | "navigation"
  | "data-display"
  | "feedback"
  | "overlays"
  | "utilities";

interface ICatalogCategory {
  id: TCategoryId;
  label: string;
  componentIds: string[];
}

interface ICatalogItem extends IComponentStand {
  category: TCategoryId;
  categoryLabel: string;
}

const CATEGORIES: ICatalogCategory[] = [
  {
    id: "forms",
    label: "Forms & actions",
    componentIds: [
      "Button",
      "Calendar",
      "CheckBox",
      "CheckBoxGroup",
      "ColorPicker",
      "DateBox",
      "Form",
      "Input",
      "InputColor",
      "InputDate",
      "InputMask",
      "InputNumber",
      "InputPhone",
      "MultiSelect",
      "RadioButton",
      "RadioGroup",
      "SearchBox",
      "Select",
      "Slider",
      "Switch",
      "TextArea",
      "TableButton",
      "UploadDragFile"
    ]
  },
  {
    id: "navigation",
    label: "Navigation",
    componentIds: [
      "Breadcrumbs",
      "Dropdown",
      "MobileSteps",
      "Pagination",
      "SegmentedControl",
      "Steps",
      "Tabs",
      "Tree"
    ]
  },
  {
    id: "data-display",
    label: "Data display",
    componentIds: [
      "Accordion",
      "Avatar",
      "Badge",
      "FileCard",
      "InfoCard",
      "Label",
      "List",
      "MapObject",
      "Tag"
    ]
  },
  {
    id: "feedback",
    label: "Feedback & status",
    componentIds: [
      "Banner",
      "CriticalError",
      "DingDing",
      "EmptyState",
      "Preloader",
      "ProgressBar",
      "Skeleton",
      "SnackBar",
      "Status"
    ]
  },
  {
    id: "overlays",
    label: "Overlays",
    componentIds: ["ModalWindow", "Popover", "Roll", "Tooltip"]
  },
  {
    id: "utilities",
    label: "Utilities",
    componentIds: ["Cluster", "Divider", "PageHeader", "Scroll", "ThemeSwitch"]
  }
];

const getCategory = (componentId: string): ICatalogCategory =>
  CATEGORIES.find(({ componentIds }) => componentIds.includes(componentId)) ??
  CATEGORIES[CATEGORIES.length - 1];

const toSearchableText = (value?: string | string[]): string =>
  Array.isArray(value) ? value.join(" ") : (value ?? "");

const getSummary = (component: IComponentStand): string =>
  toSearchableText(component.subTitle) ||
  toSearchableText(component.description) ||
  "Production-ready building block with typed, theme-aware APIs.";

const catalogItems: ICatalogItem[] = Object.values(componentsPages)
  .map(({ componentStand }) => {
    const category = getCategory(componentStand.id);

    return {
      ...componentStand,
      category: category.id,
      categoryLabel: category.label
    };
  })
  .sort(
    (first, second) =>
      (first.order ?? Number.MAX_SAFE_INTEGER) -
        (second.order ?? Number.MAX_SAFE_INTEGER) ||
      first.id.localeCompare(second.id)
  );

const ComponentsPage: React.FC = () => {
  const [query, setQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState<TCategoryId | "all">(
    "all"
  );

  const categoryCounts = useMemo(
    () =>
      catalogItems.reduce<Record<TCategoryId, number>>(
        (counts, component) => ({
          ...counts,
          [component.category]: counts[component.category] + 1
        }),
        {
          forms: 0,
          navigation: 0,
          "data-display": 0,
          feedback: 0,
          overlays: 0,
          utilities: 0
        }
      ),
    []
  );

  const filteredItems = useMemo(() => {
    const normalizedQuery = query.trim().toLocaleLowerCase();

    return catalogItems.filter((component) => {
      const isInCategory =
        activeCategory === "all" || component.category === activeCategory;
      const searchableContent = [
        component.id,
        component.title,
        component.group,
        component.subGroup,
        component.categoryLabel,
        toSearchableText(component.subTitle),
        toSearchableText(component.description)
      ]
        .filter(Boolean)
        .join(" ")
        .toLocaleLowerCase();

      return isInCategory && searchableContent.includes(normalizedQuery);
    });
  }, [activeCategory, query]);

  const releaseCount = catalogItems.filter(
    ({ status }) => status === "release"
  ).length;
  const hasFilters = query.length > 0 || activeCategory !== "all";

  const clearFilters = (): void => {
    setQuery("");
    setActiveCategory("all");
  };

  return (
    <CatalogPage aria-labelledby="components-page-title">
      <CatalogResponsiveStyles />
      <CatalogHero>
        <CatalogHeroCopy>
          <CatalogEyebrow>Component library</CatalogEyebrow>
          <CatalogTitle id="components-page-title">
            Build with confidence.
          </CatalogTitle>
          <CatalogIntro>
            Explore polished, theme-aware React building blocks designed to move
            from prototype to production without the usual handoff drag.
          </CatalogIntro>
        </CatalogHeroCopy>

        <Stats aria-label="Library coverage">
          <Stat>
            <StatValue>{catalogItems.length}</StatValue>
            <StatLabel>documented components</StatLabel>
          </Stat>
          <Stat>
            <StatValue>{releaseCount}</StatValue>
            <StatLabel>release-ready APIs</StatLabel>
          </Stat>
          <Stat>
            <StatValue>100%</StatValue>
            <StatLabel>TypeScript-first</StatLabel>
          </Stat>
        </Stats>
      </CatalogHero>

      <CatalogControls aria-label="Component catalog controls">
        <SearchLabel htmlFor="component-search">Find a component</SearchLabel>
        <SearchField>
          <SearchIcon aria-hidden="true">⌕</SearchIcon>
          <SearchInput
            id="component-search"
            type="search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search by name, purpose, or category…"
            autoComplete="off"
          />
          {query && (
            <ClearSearchButton
              type="button"
              onClick={() => setQuery("")}
              aria-label="Clear component search">
              ×
            </ClearSearchButton>
          )}
        </SearchField>

        <CategoryFilters
          role="group"
          aria-label="Filter components by category">
          <CategoryButton
            type="button"
            $active={activeCategory === "all"}
            aria-pressed={activeCategory === "all"}
            onClick={() => setActiveCategory("all")}>
            All
            <CategoryCount>{catalogItems.length}</CategoryCount>
          </CategoryButton>
          {CATEGORIES.filter(({ id }) => categoryCounts[id] > 0).map(
            (category) => (
              <CategoryButton
                key={category.id}
                type="button"
                $active={activeCategory === category.id}
                aria-pressed={activeCategory === category.id}
                onClick={() => setActiveCategory(category.id)}>
                {category.label}
                <CategoryCount>{categoryCounts[category.id]}</CategoryCount>
              </CategoryButton>
            )
          )}
        </CategoryFilters>
      </CatalogControls>

      <ResultsHeader>
        <ResultsSummary role="status" aria-live="polite">
          {filteredItems.length === catalogItems.length && !hasFilters
            ? `All ${catalogItems.length} components`
            : `${filteredItems.length} component${
                filteredItems.length === 1 ? "" : "s"
              } found`}
        </ResultsSummary>
      </ResultsHeader>

      {filteredItems.length > 0 ? (
        <ResultsGrid>
          {filteredItems.map((component) => (
            <ResultsItem key={component.id}>
              <CatalogCard
                to={`/components/${component.id}`}
                aria-label={`Open ${component.id} documentation`}>
                <CatalogCardHeader>
                  <CatalogCardLabel>{component.title}</CatalogCardLabel>
                  {component.status === "release" && (
                    <ReleaseBadge>
                      <span aria-hidden="true" /> Stable
                    </ReleaseBadge>
                  )}
                </CatalogCardHeader>
                <CatalogCardName>{component.id}</CatalogCardName>
                <CatalogCardDescription>
                  {getSummary(component)}
                </CatalogCardDescription>
                <CatalogCardFooter>
                  <span>{component.categoryLabel}</span>
                  <ViewLabel aria-hidden="true">View docs&nbsp; →</ViewLabel>
                </CatalogCardFooter>
              </CatalogCard>
            </ResultsItem>
          ))}
        </ResultsGrid>
      ) : (
        <EmptyState>
          <EmptyStateMark aria-hidden="true">⌕</EmptyStateMark>
          <h2>No components found</h2>
          <p>
            Try a broader search or reset the category filter to explore the
            full library.
          </p>
          <EmptyStateButton type="button" onClick={clearFilters}>
            Show all components
          </EmptyStateButton>
        </EmptyState>
      )}
    </CatalogPage>
  );
};

export default ComponentsPage;
